print ("*********************************")
print ("Tugas Day-1 Sistem Operasi Kelas B")
print ("*********************************")
print ("Nama : Naomi Dwi Anggraini")
print ("NPM  : 21083010010")
print ("*********************************")
print ("Notes:")
print ("*********************************")
print ("Hello People")
print ("ini adalah script bash pertamaku di linux")
